import main_crawler

def test_wikipedia_crawler():
    
    assert  main_crawler.wikipedia_crawler('https://id.wikipedia.org/wiki/Jerman') == {'title': 'Jerman', 'snippet': 'Republik Federal Jerman (bahasa Jerman: Bundesrepublik Deutschland) adalah negara berbentuk federasi di Eropa Barat. Negara ini memiliki posisi ekonomi dan politik yang sangat penting di Eropa maupun di dunia. Dengan luas 357.021 kilometer persegi (kira-kira dua setengah kali pulau Jawa) dan penduduk sekitar 82 juta jiwa, negara dengan 16 negara bagian (Bundesland, jamak: Bundesländer) ini menjadi anggota kunci organisasi Uni Eropa (penduduk terbanyak), penghubung transportasi barang dan jasa an', 'panjang_snippet': 500}, 'Hasilnya Masih Salah' 
    assert main_crawler.wikipedia_crawler('https://id.wikipedia.org/wiki/Jack_Ma') == {'title': 'Jack Ma', 'snippet': 'Jack Ma (lahir di Hangzhou, Zhejiang, Tiongkok, 10 September 1964; umur 54 tahun) merupakan seorang pebisnis berkebangsaan Tionghoa. Dia merupakan pendiri sekaligus Chairman Eksekutif dari Alibaba Group, perusahaan e-commerce terbesar di Tiongkok[2]. Dia merupakan warga China Daratan pertama yang pernah muncul di majalah Forbes dan terdaftar sebagai biliuner dunia. Pada 2015, ia masuk dalam daftar orang paling berpengaruh di dunia pada urutan ke-22[3].\nSebagai seorang miliader, ternyata Jack Ma ', 'panjang_snippet': 500}, 'Hasilnya Masih Salah'
    assert main_crawler.wikipedia_crawler('https://id.wikipedia.org/wiki/Hangzhou') == {'title': 'Hangzhou', 'snippet': 'Hangzhou (Hanzi: 杭州) merupakan ibukota terbesar di provinsi Zhejiang di pesisir timur RRT.[3] Terletak di kepala Teluk Hangzhou di pantai Cina antara Shanghai dan Ningbo. Hangzhou dikenal sebagai ujung selatan Grand Canal dan telah menjadi salah satu kota yang paling terkenal dan makmur di Cina, sebagian karena pemandangan alam yang indah. Danau Barat, salah satu situs warisan dunia UNESCO, merupakan daya tarik yang paling terkenal di Hangzhou.\nHangzhou diklasifikasikan sebagai kota sub-provinsi', 'panjang_snippet': 500}, 'Hasilnya Masih Salah'
    assert main_crawler.wikipedia_crawler('https://id.wikipedia.org/wiki/Suami_untuk_Mak') == 'Halaman Masih Kosong!', 'Halaman Sudah Isi'
 
def test_url_checker():
    assert main_crawler.url_checker('facebook.com/wikipedia.org') == 'Url Tidak Valid!', 'Masih Kurang Tepat'
    assert main_crawler.url_checker('https://en.wikipedia.org/wiki/Hangzhou') == {"title": "Hangzhou", 'snippet': "Hangzhou (Mandarin: [xa??.??o?u] (listen); local dialect: /??? tse?/) formerly romanized as Hangchow, is the capital and most populous city of Zhejiang Province in East China.[2] It sits at the head of Hangzhou Bay, which separates Shanghai and Ningbo. Hangzhou grew to prominence as the southern terminus of the Grand Canal and has been one of the most renowned and prosperous cities in China for much of the last millennium. The city's West Lake, a UNESCO World Heritage site immediately west of th",'panjang_snippet': 500}, 'Hasilnya Masih Salah'
    #assert main_crawler.url_checker() == ''
    #assert main_crawler.url_checker() == ''
